version: '3'
services:
  marqo:
    image: marqoai/marqo:latest
    ports:
      - "8882:8882"


  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MARQO_URL=http://marqo:8882
    volumes:
      - dataset_data:cache
    depends_on:
      - marqo

volumes:
  dataset_data: